### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by Judge-Paul** [carlosvaldesweb/tiptap-extension-upload-image#2]
@carlosvaldesweb 
Thanks for creating this awesome library it just works right out the box with tiptap, but can you add typescript support 

![Screenshot from 2024-05-03 22-56-19](https://github.com/carlosvaldesweb/tiptap-extension-upload-image/assets/110723341/a0e7ba0d-f7ac-47e0-89b0-05242d24841e)
I keep getting this error and the only way I've been able to solve it is by making the editor to be of type any
![image](https://github.com/carlosvaldesweb/tiptap-extension-upload-image/assets/110723341/144eb83f-5524-404f-988b-238b321d4fa8)

**Comment by carlosvaldesweb** [comment]
Hello @Judge-Paul , i've added Typescript support in #4
