### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by julia-and** [carlosvaldesweb/tiptap-extension-upload-image#3]
Hello,

This is a great project, and I learned a lot from it!

Unfortunately, without a license specified, no one can legally use this project. Please consider adding an open-source license as described here: 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

Thank you!

**Comment by carlosvaldesweb** [comment]
Added, thank you.
